---
title: "Rezago habitacional en México"
author: "Will Santana"
based_on: "Trabajo de Claudio @claudiodanielpc"
date: "12/29/2020"
output:
  prettydoc::html_pretty:
    theme: leonids
    highlight: github
---

```{r setup, include=FALSE, echo=TRUE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = T)
```


```{r Descripción}
# El propósito de éste análisis es meramente educativo.
```


```{r Cargamos las librerias}
library(plyr); library(dplyr)
library(tidyverse)
library(readxl)
library(readr)
library(srvyr)
library(ggplot2)
library(ggthemes)
```


```{r Leemos los datos desde archivos}
# Inicializamos las variables con las rutas de los archivos
vivienda_file <- "data/enigh/viviendas.csv"
catalogo_file <- "data/claves.xlsx"

# Cargamos los datos:
# Vivienda
vivi <- read.csv(vivienda_file, na.strings = "NA")
# Catálogo de entidades
cata <- readxl::read_excel(catalogo_file, range ="A4:B36")
# Modificamos el nombre de las columnas del dataframe cata
names(cata) <- c("cve_ent", "nom_ent")

# Eliminamos variables innecesarias
rm(vivienda_file)
rm(catalogo_file)
```


```{r Cargamos los datos}

# Si la longitud de la variable folio es de nueve, le agregamos un cero (0)
# al inicio para formatear todos los códigos a dos dígitos, en caso contrario
# se lee el código de dos dígitos, sin agregar nada.
vivi <- vivi %>% 
  mutate(cve_ent = ifelse(nchar(folioviv) == 9,
                          paste0("0", str_sub(folioviv, 1, 1)),
                          str_sub(folioviv, 1, 2)))

# Unimos los dos dataframe y lo asignamos a vivienda
vivienda <- full_join(vivi, cata, by = "cve_ent")

# Vivienda Nacional
vivienda_nacional <- vivienda

rm(vivi)
rm(cata)
```


```{r Aplicamos la condición para identificar el tipo de rezago}
# Debido a que la columna mat_pisos contiene factores, debemos transformarla
# a valores numéricos
vivienda <- transform(vivienda, mat_pisos = as.numeric(mat_pisos))

# Buscamos bajo el siguiente criterio:
# Se cumple: rezago = "En rezago"
# No se cumple: rezago = "Fuera de rezago"
# Nota: Debido que al convertir la varibale 'mat_pisos', el caracter '&'
# se convierte en 1, el valor más grande que tenía antes, el 3, se convierte
# en 4, cambiamos la condición de:
# (mat_pisos == 1) |
# a
# (mat_pisos == 2) |
vivienda <- vivienda %>%
  mutate(rezago =
           case_when(((tot_resid/num_cuarto) > 2.5) |
                       ((mat_pared >= 1) & (mat_pared <= 6)) |
                       ((mat_techos >= 1) & (mat_techos <= 4)) |
                       ((mat_techos >= 6) & (mat_techos <= 7)) |
                       (mat_techos == 9) |
                       (mat_pisos == 2) |
                       (excusado == 2) ~ "En rezago",
                     TRUE ~ "Fuera de rezago"))
```


```{r Calculamos el rezago total}
# En los dos factores: "En rezago" y "Fuera de rezago"
rezago_total <- vivienda %>% 
  group_by(rezago) %>%
  dplyr::summarize(total = sum(factor), .groups = "drop") %>% 
  mutate(pct = round(total / sum(total) * 100, 2))

rezago_total
```


```{r Gráfico: Rezago total (sencillo)}
# Colores de gráfico
colores <- c("#E13F29", "#D69A80", "#FFFFFF")

slices <- c(rezago_total$total)
lbls <- c("En rezago", "Fuera de rezago")
pct <- round(slices/sum(slices)*100, 2)
lbls <- paste(lbls, pct)
lbls <- paste(lbls, "%", sep="")
# Gráfico de pastel (pie chart), con los datos de rezago
pie(slices, labels = lbls, edges = 200, main = "México. Parque habitacional por condición de rezago, 2018", col = colores, border = "white")
```


```{r Gráfico: Rezago total (ggplot)}
# Colores de gráfico
colores <- c("#E13F29", "#D69A80", "#FFFFFF")

slices <- rezago_total$pct
pct <- round(slices/sum(slices)*100, 2)
lbls <- rezago_total$pct
lbls <- paste(lbls, "%", sep="")

df.data <- data.frame(
  Categorías = rezago_total$rezago,
  Valores = rezago_total$pct,
  Etiquetas = lbls,
  lab.ypos = c(87, 40)
)

ggplot(df.data, aes(x = "", y = Valores, fill = Categorías)) +
  geom_bar(width = 1, stat = "identity", color = "white") +
  coord_polar("y", start = 90) +
  geom_text(aes(y = lab.ypos, label = Etiquetas), color = "white", size = 4) +
  scale_fill_manual(values = colores) +
  ggtitle("México. Parque habitacional por condición de rezago, 2018 \n (%)") +
  theme_void() +
  theme(plot.title = element_text(color = "black", size = 14, face = "bold", hjust = 0.5))

ggsave("imagenes/Figura_1.png", plot = last_plot(), width = 9, height = 4, units = "in", dpi = 150)
rm(df.data)
```


```{r Calculamos el rezago por entidad}
rezago_entidad <- vivienda %>% 
  srvyr::group_by(nom_ent, rezago) %>%
  dplyr::summarize(rez_ent = sum(factor), .groups = "drop") %>% 
  filter(rezago != "Fuera de rezago") %>% 
  mutate(pct_ent = rez_ent / sum(rez_ent) * 100)

rezago_entidad
```


```{r Gráfico: Rezago por entidad}
ggplot(rezago_entidad,
       aes(x=pct_ent, y=reorder(nom_ent,pct_ent))) +
  geom_bar(stat="identity", color = "white", position="dodge") +
  geom_col(aes(fill = pct_ent)) +
  scale_fill_gradient(low=colores[2], high = colores[1]) +
  labs(
    title = "Porcentaje del total del rezago habitacional",
    subtitle = "Fuente: INEGI. Encuesta Nacional de Ingresos y Gastos de los Hogares (ENIGH) 2018",
    caption = "@willshDev",
    fill = "Porcentaje",
    x = "",
    y = ""
  ) +
  theme(plot.title = element_text(color = "black", 
                                  size = 14, 
                                  face = "bold", 
                                  hjust = 0.5,
                                  lineheight = 0.9),
        plot.subtitle = element_text(color = "black",
                                     size = 8, 
                                     hjust = 0.5,
                                     lineheight = 0.9))

ggsave("imagenes/Figura_2.png", plot = last_plot(), width = 6, height = 9, units = "in", dpi = 600)
```